### PR TITLE
[CIF-135] Move metrics to their own files

### PR DESCRIPTION
**Pull request by jterry64**

### CODE REVIEW

**Comment by S-AI-F** [comment]
I tested the indicators with the new structure, I had to add the "points" in the "metrics\_init" file for loading well the metrics sub-modules. The indicators work well, only "natural_areas" metric is missing from the list. Can you please add it?

**Comment by chrowe** [comment]
@S-AI-F can you confirm this works for you in your notebooks?

**Comment by S-AI-F** [comment]
Yes it is working

**Review by chrowe — APPROVED** [review]
Made a few edits. Looks good to me.

**Pull request merged**
