### PR TITLE
add tutorial notebook

### PR DESCRIPTION
**Pull request by S-AI-F**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [ ] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by chrowe** [comment]
@S-AI-F just a reminder to update this so we can merge it in. Not my comment above with some suggested changes.

**Comment by S-AI-F** [comment]
@chrowe Is it ok if we ignore this pull request? I created a new branch for the tutorial notebook based on the updated framework structure.

**Comment by chrowe** [comment]
Sure, if we have no plans to merge it we could just delete it.

**Comment by S-AI-F** [comment]
@chrowe yes i don't think that we will merge it! I will delete it.

**Pull request closed without merging**
