### PR TITLE
add ERA 5 highest temperature layer

### PR DESCRIPTION
**Pull request by weiqi-tori**
Description: Add layer for https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-land?tab=overview
JIRA ticket is https://gfw.atlassian.net/browse/CIF-198
Test by running pytest layers.py::test_era_5_hottest_day
TODO: CDS API key issue

### CODE REVIEW

**Comment by chrowe** [comment]
1. Make this raster layer with all the values
2. Create a metric with the unit conversions

**Comment by chrowe** [comment]
@weiqi-tori can you add api key docs to the readme

**Review by chrowe — CHANGES_REQUESTED** [review]
@weiqi-tori can you add a test for the layer and the metric and an example notebook in he notebooks/layers folder?

**Comment by weiqi-tori** [comment]
Added tests for layer and metric @chrowe

**Review by chrowe — APPROVED** [review]

**Pull request merged**
