### PR TITLE
Feature/transit stops osm

### PR DESCRIPTION
**Pull request by weiqi-tori**
https://gfw.atlassian.net/browse/CIF-212

### CODE REVIEW

**Review by tedw0ng — CHANGES_REQUESTED** [review]
Please also add these values to 'railway': 'subway_entrance', 'station'

**Comment by weiqi-tori** [comment]
> Please also add these values to 'railway': 'subway_entrance', 'station'

Gotcha, added

**Review by kcartier-wri — COMMENTED** [review]
If possible, it may be worthwhile adding a docstring to the OpenStreetMapClass that describes the high-level criteria for including the specific OSM features in the class. What is the underlying goal. Is it simply that the Data Scientists have requested these specific features or are we trying to produce a “base map” of some sort toward some goal? This would allow us to determine if the set is complete.

For example, given that wetlands are a critical environmental landform, why are we not currently specifying ‘natural’:[wetland’] under water?

Is there an internal page that describes how we decide which features to include and why? 

It may also be useful to include a pointer to the OSM features page [Map features - OpenStreetMap Wiki](https://wiki.openstreetmap.org/wiki/Map_features)

**Comment by S-AI-F** [comment]
The OSM features are used for calculating the indicators that are served in the dashboard and not for basemap (fir this case). For exemple, 'open space' and 'health sites' are used for calculating proximity to open space areas or health service. The indicators methods are defined in the technical note used for this work. Agree that we might probably have documentation or links to the published technical in the code base.

**Comment by S-AI-F** [comment]
The tech note describinh the indicator methids and how the layers are defined: https://www.wri.org/research/calculating-indicators-global-geospatial-datasets-urban-environment

**Review by chrowe — APPROVED** [review]
Looks good to me

**Pull request merged**
