### PR TITLE
draft developer guide

### PR DESCRIPTION
**Pull request by weiqi-tori**
## Did you read the Contributor Guide?

- Yes, I have read [How to contribute](https://github.com/wri/cities-cif#How-to-contribute)

- No, I haven't read it.

## Is this PR related to a JIRA ticket?

- Yes, the URL of the associated JIRA ticket is https://gfw.atlassian.net/browse/CIF-XXX. The PR name follows the format `[CIF-XXX] my subject`.

- No, this is a documentation update. The PR name follows the format `[DOCS] my subject`.

## Did this PR include necessary documentation updates?

- Yes, I am adding a new API feature.
- Yes, I have updated the documentation update.
- No, this PR does not affect any public API so no need to change the docs.

### CODE REVIEW

**Review by jterry64 — APPROVED** [review]
This looks good to me! Once you merge it I might add additional details for adding Python code.

**Comment by chrowe** [comment]
I think I might restructure this a bit to focus more on the indicators first.

**Comment by S-AI-F** [comment]
Agree with Chris, it would be better to focus on adding layers and indicators for this doc, and keep the description of adding a new city in carto in a sperate doc (probably as part of API or dashboard). More details about python code are welcome @jterry64

**Comment by chrowe** [comment]
## Updates
### Developer docs
1. Integrated Saif's additions and my changes into Tori's work
2. Moved `Tests` secion from Readme
3. Updated links within the repo to use relative links so they work locally and on any branch

### Readme 
1. Added overview
2. Added interactive GEE auth guide
3. Removed this from the main readme. Not sure if it is worth trying to add any of it to the developer docs

```
The code has the following structure:

- The `layers` subpackage contains all data raster or vector data used for metrics inhering from the base `Layer` class
    - All layers must implement a `get_data` function that accept a bbox and returns either:
        - A rioxarray-format xarray with the data in the bbox for raster data
        - A GeoPandas DataFrame for vector data
    - rioxarray format means only `x` and `y` dimensions, in that order
    - New layers based off existing layers should re-use that layer's data
    - The Layer subclass will handle actually running zonal statistics
- Pre-canned "indicator" analyses are defined as functions in `metrics.py`
    - Indicator analyses should use calculate using layer classes and `Layer` zonal stats API
- To utilize dask for bigger jobs, dask cluster must be initialized outside this library
```

**Comment by chrowe** [comment]
I went ahead and merged so I could share with Ted but feel free to suggest any updates or corrections!

**Pull request merged**
